#!/bin/bash

if [[ -z $ROOTPASS ]]; then
    ROOTPASS="$(python3 -c 'import os; print(os.urandom(64).hex())')"
fi
if [[ -z $USERPASS ]]; then
    USERPASS="$(python3 -c 'import os; print(os.urandom(64).hex())')"
fi
echo "root:${ROOTPASS}" > rootpasswd
echo "alpine:${USERPASS}" > passwd
